import React, { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { setCurrentUser } from 'redux/user/user.actions'
import tokenomics from 'images/tokenomics.png'
import Overview from 'images/tokenomics-overview.png'
import Chart from 'images/token.png'
import KabyToken from 'images/play-to-earn.png'
import KabyEquip from 'images/kaby-equip.png'
import KabyNonNFT from 'images/non-nft.png'
import KabyNFT from 'images/kaby-nft.png'
import './Tokenomics.scss'

const Tokenomics = (props) => {
  const dispatch = useDispatch()

  useEffect(() => {
    const testUser = {
      name: 'Rikkei',
      phone: '0123456789',
    }
    dispatch(setCurrentUser(testUser))
  }, [dispatch])

  return (
    <div>
      <div className="tokenomics-content">
        <div className="cpn-head">
          <h2 className="cpn-head-title">
            <strong> Kaby </strong> Tokenomics
          </h2>
        </div>
        <div className="tokenomics-content-header">
          <span className="tokenomics-content-header-up">Kaby Assets</span>
          <span className="tokenomics-content-header-down">
            Kaby Arena utilizes 3 main assets which are deployed on polygon.
          </span>
        </div>
        <div className="tokenomics-content-body">
          <div className="row intro">
            <div className="col-lg-6">
              <div className="box-pad gfx-pic section-head ">
                <h2 className="fam-font title title-s2">kaby assets</h2>
              </div>
              <img
                src={tokenomics}
                className="img-fluid "
                alt="tokenomics"
                width="640px"
                height="440px"
              />
            </div>
            <div className="col-lg-6 row intro-content">
              <div className="col-lg-6">
                <div>
                  <img alt="kaby" width="55px" height="55px" src={KabyToken}></img>
                </div>
                <div className="intro-text">
                  <h5>Kaby Token</h5>
                  <ul>
                    <li>ERC 20 token</li>
                    <li>Main currency</li>
                    <li>Open treasure chests</li>
                    <li>Echange for resources or in-game upgrades</li>
                    <li>Mint NFT from free heroes</li>
                    <li>Buy/rent NFT assets</li>
                    <li>Wage on PvP battles</li>
                    <li>Staking for interest</li>
                  </ul>
                </div>
              </div>
              <div className="col-lg-6">
                <span>
                  <img alt="kaby" width="55px" height="55px" src={KabyEquip}></img>
                </span>
                <div className="intro-text">
                  <h5>Kaby equipments</h5>
                  <ul>
                    <li>ERC 1155 token</li>
                    <li>Rewarded from PvE</li>
                    <li>Generated by opening treasure chests</li>
                    <li>Can be sold/bought on the Kaby marketplace</li>
                  </ul>
                </div>
              </div>
              <div className="col-lg-6">
                <div>
                  <img alt="kaby" width="55px" height="55px" src={KabyNonNFT}></img>
                </div>
                <div className="intro-text">
                  <h5>Kaby Non NFT Heroes</h5>
                  <ul>
                    <li>Not token</li>
                    <li>Free reward from PvE mode</li>
                    <li>Untradable</li>
                    <li>Can be ascended to NFT Heroes using Kaby token</li>
                  </ul>
                </div>
              </div>
              <div className="col-lg-6">
                <div>
                  <img alt="kaby" width="55px" height="55px" src={KabyNFT}></img>
                </div>
                <div className="intro-text">
                  <h5>Kaby NFT Heroes</h5>
                  <ul>
                    <li>ERC 721 token</li>
                    <li>Can evolve from battles</li>
                    <li>Can be sold/bought on the Kaby marketplace or any other NFT markets</li>
                    <li style={{ visibility: 'hidden' }}></li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="tokenomics-chart row">
          <div className="col-lg-6 tokenomics-overview">
            <div className="box-pad d-lg-flex justify-content-center  ">
              <h2 className="fam-font title title-s2">tokenomics</h2>
            </div>
            <div>
              <img
                src={Overview}
                className="img-fluid"
                alt="token overview"
                width="770px"
                height="520px"
              />
            </div>
          </div>

          <div className="col-lg-6">
            <div>
              <img
                src={Chart}
                className="img-fluid"
                alt="token overview"
                width="770px"
                height="640px"
              />
            </div>
          </div>

          <div className="tokenomics-content-chart-image"></div>
        </div>
      </div>
    </div>
  )
}

export default Tokenomics
