export const TRANSACTION = {
  BUY: 'buy',
  OFFER: 'offer',
  TAKE: 'take_offer',
  CANCEL_OFFER: 'cancel_offer',
  LIST: 'list',
  DELIST: 'delist',
  APPROVE: 'approve',
  SUMMON: 'summon',
  STAKE: 'stake',
  UNSTAKE: 'unstake',
  CLAIM: 'claim',
  UPGRADE: 'upgrade',
  GIFT: 'gift',
  BUYITEM: 'buy_item',
  LISTITEM: 'list_item',
  DELISTITEM: 'delist_item',
  KABYSTAKE: 'kaby_stake',
  KBUSDSTAKE: 'kabybusd_stake',
}
